import type { Metadata } from "next";
import "@/styles/global.css";
import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <AppHeader />

        <main className="flex-grow">{children}</main>

        <AppFooter />
      </body>
    </html>
  );
}
